"""M4 über die API: Auto-Kalendereintrag, Ferien/Feiertage (gemockt), Jahresplanung."""


def test_lesson_date_syncs_auto_calendar_entry(client, auth):
    l = client.post("/api/lessons", json={"title": "Balladen", "subject": "Deutsch", "date": "2025-09-15"}).json()
    autos = [c for c in client.get("/api/calendar").json() if c["lessonId"] == l["id"]]
    assert len(autos) == 1 and autos[0]["entryDate"] == "2025-09-15" and autos[0]["autoGenerated"] is True

    client.put(f"/api/lessons/{l['id']}", json={"date": "2025-09-22"})
    autos = [c for c in client.get("/api/calendar").json() if c["lessonId"] == l["id"]]
    assert autos[0]["entryDate"] == "2025-09-22"  # zieht mit

    client.put(f"/api/lessons/{l['id']}", json={"date": None})
    assert [c for c in client.get("/api/calendar").json() if c["lessonId"] == l["id"]] == []  # weg


def test_lesson_delete_removes_auto_entry(client, auth):
    l = client.post("/api/lessons", json={"title": "X", "subject": "WTH", "date": "2025-09-10"}).json()
    assert any(c["lessonId"] == l["id"] for c in client.get("/api/calendar").json())
    client.delete(f"/api/lessons/{l['id']}")
    assert not any(c.get("lessonId") == l["id"] for c in client.get("/api/calendar").json())


def test_school_dates_fetched_and_range_filtered(client, auth, monkeypatch):
    from src.lib import holidays
    monkeypatch.setattr(holidays, "collect_school_dates", lambda *a, **k: [
        {"kind": "feiertag", "name": "Tag der Deutschen Einheit", "start_date": "2025-10-03", "end_date": "2025-10-03", "source": "test"},
        {"kind": "ferien", "name": "Herbstferien", "start_date": "2025-10-06", "end_date": "2025-10-18", "source": "test"},
        {"kind": "ferien", "name": "Ausserhalb", "start_date": "2024-01-01", "end_date": "2024-01-05", "source": "test"},
    ])
    sy = client.post("/api/school-years", json={"label": "2025/2026", "startDate": "2025-08-01", "endDate": "2026-07-15"}).json()
    names = [d["name"] for d in client.get(f"/api/school-years/{sy['id']}/dates").json()]
    assert "Herbstferien" in names and "Tag der Deutschen Einheit" in names
    assert "Ausserhalb" not in names  # außerhalb der Schuljahresspanne gefiltert


def test_planning_preview(client, auth):
    sy = client.post("/api/school-years", json={"label": "2025/2026", "startDate": "2025-08-11", "endDate": "2026-06-30"}).json()
    cls = client.post("/api/classes", json={"name": "8a", "subject": "Deutsch", "grade": 8, "track": "RS", "weeklyHours": 3}).json()
    for i, (code, ustd) in enumerate([("LB1", 15), ("LB2", 22)], 1):
        client.post("/api/lernbereiche", json={"subject": "Deutsch", "grade": 8, "track": "RS",
                                               "code": code, "title": f"Bereich {code}", "richtwertUstd": ustd, "sortOrder": i})
    res = client.post("/api/planning/preview", json={"schoolYearId": sy["id"], "classId": cls["id"]}).json()
    assert res["teachingWeeks"] > 0
    assert res["planned"] == 2
    assert res["blocks"][0]["code"] == "LB1"
    assert res["blocks"][0]["endDate"] < res["blocks"][1]["startDate"]
